### ISSUE TITLE
Can't run nengo_ocl with nengo development version

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_ocl#115]
It gives this exception:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-c06682d531d2> in <module>()
      1 import nengo_ocl
----> 2 with nengo_ocl.Simulator(model) as sim:
      3     sim.run(4.4)

/home/jgosmann/.virtualenvs/bleeding-edge/lib/python2.7/site-packages/nengo_ocl-1.0.1.dev0-py2.7.egg/nengo_ocl/simulator.pyc in __init__(self, network, dt, seed, model, context, n_prealloc_probes, profiling, ocl_only, planner, shrink_cache)
    284                 "This simulator only supports Nengo %s.x (got %s)" %
    285                 ('.'.join(str(i) for i in latest_nengo_version_info[:2]),
--> 286                  nengo.__version__))
    287         elif nengo.version.version_info > latest_nengo_version_info:
    288             warnings.warn("This version of `nengo_ocl` has not been tested "

ValueError: This simulator only supports Nengo 2.1.x (got 2.2.0.dev0)
```

**Comment by tbekolay** [comment]
Yeah... not sure what the right course of action is here; in a sense, this is the desired effect, because there's no guarantee OCL will run with the dev version of Nengo. The easy workarounds are to check out the `v2.1.2` tag, or edit `nengo/versions.py` version locally.

If we want to make sure that the dev version will always work, then one option is to only increment the patch version after a Nengo release, even if the next release ends up incrementing the minor version.

**Comment by jgosmann** [comment]
> The easy workarounds are to check out the v2.1.2 tag

I'm on my own branch.

> or edit nengo/versions.py version locally.

messy

Why can't we just produce a warning?

**Comment by tbekolay** [comment]
> Why can't we just produce a warning?

The thing is, even if it's messy, as devs it's easy to do this kind of workaround. The error is intended for end users who have upgraded nengo but not nengo_ocl, then try to use nengo_ocl expecting it to just work. The error forces them to upgrade, where a warning would just be ignored. We do raise a warning rather than an error if they have a different patch version, but not a different minor version, hence why upping the patch version after a release is a possible solution.

**Comment by jgosmann** [comment]
> even if it's messy, as devs it's easy to do this kind of workaround

To me it's quite annoying because I have to do it on potentially a number of branches, but can't commit it which constantly displays files as modified, might need stashing of those changes for switching branches (or if I commit it, I have to remove that commit later in the PR). Also, the version information would be unreliable when I want to check what version I am using.

For me it's actually more convenient to completely remove the version check from nengo_ocl than changing the nengo version number.

I would be fine with just updating the patch version after a release. An alternative idea (probably a little bit more work) would be an rc option to deactivate the version check.

**Comment by tbekolay** [comment]
> completely remove the version check from nengo_ocl than changing the nengo version number

Sure, that's another valid workaround... I was just listing the few that came to mind off the top of my head.
